nav:
  home: /
  about: /关于/
  article: /文章/
  Search: /Search/
  projects: https://github.com/whiteleibniz

projects_url: https://github.com/whiteleibniz

customize:
    gravatar:
        email: nologic@126.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/whiteleibniz
        weibo: https://weibo.com/p/1005052543259442
        qq: https://weibo.com/p/1005052543259442
        #linkedin:
    show_all_posts: false
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-121919637-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus: